spring.application.name=sstc-backend
server.port=8080

# Importar variables de entorno desde el archivo .env
spring.config.import=optional:file:.env[.properties]

# Las siguientes propiedades se cargan desde el archivo .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.h2.console.enabled=false
springdoc.swagger-ui.path=/docs